// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm6nUGdTCKVnf8c-gD7LNKzv3R7q6Mtdw',
    appId: '1:832606318566:web:cc9a2218fe590b9e0b7027',
    messagingSenderId: '832606318566',
    projectId: 'week-7-72181',
    authDomain: 'week-7-72181.firebaseapp.com',
    storageBucket: 'week-7-72181.appspot.com',
    measurementId: 'G-Y3EGK5XS29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-GeoEIsAbe187D5H70LAJdnU0tRlMtVE',
    appId: '1:832606318566:android:e17f96db1b3f8d100b7027',
    messagingSenderId: '832606318566',
    projectId: 'week-7-72181',
    storageBucket: 'week-7-72181.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjc8REjs3EXg3VTY6UZiQ1jErAhVK9rbM',
    appId: '1:832606318566:ios:319c6a0006ee81720b7027',
    messagingSenderId: '832606318566',
    projectId: 'week-7-72181',
    storageBucket: 'week-7-72181.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjc8REjs3EXg3VTY6UZiQ1jErAhVK9rbM',
    appId: '1:832606318566:ios:476ce6df32123d3d0b7027',
    messagingSenderId: '832606318566',
    projectId: 'week-7-72181',
    storageBucket: 'week-7-72181.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
